### ISSUE TITLE
Consider separating "authentication / authorization" from "communication"

### ISSUE THREAD

**Issue by cstettler** [ISA-Principles/isa-principles.org#10]
Authentication and authorization are discussed as part of principle 5 "communication" and more, reasoning 5. While authentication is in some way related to communication in the sense that credentials / security context information have to be communicated between different modules, communication is not the only aspect discussed: the reasoning section talks about additional aspects unrelated to communication (i.e. SSO, module-specific authorization). 

Those aspects can be seen as important enough to motivate a separate principle and reasoning for authentication and authorization:

- authentication should be done on macro-level in order to allow a single authentication towards the system as a whole from the user perspective
- authorization requires knowledge about the domain and therefore should be realized on a per-module level

**Comment by ewolff** [comment]
I think that makes sense. I would be eager to hear what others think.

**Comment by ewolff** [comment]
Roles should be clarified: result of authentication, part of macro architecture, can be used for authorization and rights.

**Comment by ewolff** [comment]
Result of face 2 face discussion: Will be separated.

**Comment by ewolff** [comment]
Fixed by #19 - however, it is not just authorization but all meta data.
