### ISSUE TITLE
Motivate earlier / more prominent in what context ISA principles apply

### ISSUE THREAD

**Issue by cstettler** [ISA-Principles/isa-principles.org#11]
The current website "starts" straight away with the description of the principles and the reasoning behind them, but only mentions "far back" in the FAQ section in what ISA principles apply (paragraph about "no silver bullet").

Describing earlier for what type of systems ISA principles are useful or what type of properties/
 or requirements must be around in order to gain by applying ISA principles would set the stage early enough.

**Comment by ewolff** [comment]
I think that makes a lot of sense. We should change index.md accordingly. Do you want to do a PR?

**Comment by ewolff** [comment]
I took a look at the index.md - actually it starts by discussing how ISA compares to microservices and SCS. However, I added a link to the FAQ. I hope this helps.
